# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0002_auto_20151013_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactplus',
            old_name='submit',
            new_name='submit_button_text',
        ),
        migrations.AlterField(
            model_name='contactplus',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_contact_plus_contactplus', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='contactplus',
            name='recipient_email',
            field=models.EmailField(default='rene@fleschenberg.net', max_length=254, verbose_name='Email of recipients'),
        ),
    ]
