# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-01 20:34
from __future__ import unicode_literals

import cmsplugin_contact_plus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0003_auto_20161102_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactplus',
            name='recipient_email',
            field=models.EmailField(default=cmsplugin_contact_plus.models.get_default_from_email_address, max_length=254, verbose_name='Email of recipients'),
        ),
    ]
