# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-21 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0004_auto_20170410_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='css_classes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CSS classes'),
        ),
    ]
