# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 12:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0005_auto_20180126_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafield',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated list of tags.', max_length=250, null=True, validators=[django.core.validators.RegexValidator('^([a-z-_0-9]+,\\s*)*[a-z-_0-9]+$')], verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='contactplus',
            name='template',
            field=models.CharField(choices=[('cmsplugin_contact_plus/contact.html', 'contact.html')], default='cmsplugin_contact_plus/contact.html', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='date_processed',
            field=models.DateTimeField(blank=True, help_text='Date the Record was processed.', null=True),
        ),
    ]
